version: '3'

services:
  tt-db:
    image: mysql:5.7.27
    command:
      - --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: 'travel-together'

  tt-nginx:
    image: nginx:1.17.3
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/site-enabled/:/etc/nginx/site-enabled/
    ports:
      - 80:80
      - 443:443

  tt-api:
    image: tt-api:latest
    build:
      context: .
      dockerfile: dev.Dockerfile
    restart: 'always'
    volumes:
      - ./:/travel-together/
    ports:
      - 3000:3000
